# Sample configuration for MDJourney development and testing.

# Directory to monitor for new or modified files.
# Use a relative path for easy local testing.
watchDirectory: '/Users/u0139314/CodeDump/sandbox/monitor/data'

# Directory containing custom Jinja2 templates for rendering.
templateDirectory: '/Users/u0139314/CodeDump/sandbox/mdjourney/packaged_schemas'

# A list of glob patterns to determine which files to monitor.
# This is highly flexible.
# Example 1: Monitor everything: ['*']
# Example 2: Monitor only markdown and text files: ['*.md', '*.txt']
watchPatterns:
  - '*'
